### ISSUE TITLE
don't bump multiple times on multipe tasks

### ISSUE THREAD

**Issue by nichtich** [kswedberg/grunt-version#11]
I tried to bump version on multiple files with multiple prefixes:

```
version: {
            package: {
                src: ['package.json', 'bower.json'],
            },
            module: {
                options: {
                    prefix: "\\('version',\\s*'"
                },
                src: ['src/example.js'],
            },
        }
```

Then `grunt version::patch` will increment version in the files listed in `package` and increment twice (e.g. 1.0.0 to 1.0.2) in the files listed in `module`. A workaround is do two calls: 

    grunt version:package:patch
    grunt version

I think the current behaviour is a bug because nobody wants to bump version twice.

**Comment by vpratfr** [comment]
You can fix that behaviour by putting the package as the last file to be updated:

        version: {
            bower: {
                src: ['package.json', 'bower.json'],
            },
            module: {
                options: {
                    prefix: "\\('version',\\s*'"
                },
                src: ['src/example.js'],
            },
            package: {
                src: ['package.json'],
            },
        }

**Comment by kswedberg** [comment]
@vpratfr, thanks for that workaround. And @nichtich, thanks for the bug report. Sorry I haven't gotten to this yet. It's a little tricky because of the way grunt deals with tasks sequentially. I'll look into it, though, to see if I can find a more robust solution.

**Comment by vpratfr** [comment]
@kswedberg Have you had a look at grunt-bump ? it does a nice job at bumping version numbers (but is missing the prefix feature needed by WordPress plugin devs)

**Comment by kswedberg** [comment]
@vpratfr yeah, grunt-bump looks nice. It's not a multi task,though, so it operates a little differently.

**Comment by kswedberg** [comment]
@nichtich One other way you can work around the problem is to set the `pkg` option like this:

```js
version: {
            options: {
                pkg: grunt.file.readJSON('package.json')
            },
            package: {
                src: ['package.json', 'bower.json'],
            },
            module: {
                options: {
                    prefix: "\\('version',\\s*'"
                },
                src: ['src/example.js'],
            },
        }
```
