### ISSUE TITLE
Update to specific version number

### ISSUE THREAD

**Issue by miguelmich** [kswedberg/grunt-version#13]
Is there an option to set a specific version to update?

I like to change grunt config values dynamically so It would be great to have an option to do this in case that I'd want to overwrite the version number.

Thanks in advance

**Comment by kswedberg** [comment]
You can do change use a literal version number by doing something like this: `grunt version:someTarget:2.1.0`. That would change the version to 2.1.0.

**Comment by miguelmich** [comment]
Oh thanks I didn't see it on docs, and can I do it skipping targets like this: `grunt version::2.1.0`?

**Comment by kswedberg** [comment]
I just added it to the docs :) , so I appreciate your asking the question. Yes, you should be able to do `grunt version::2.1.0`.

**Comment by miguelmich** [comment]
Thanks a lot! I love this plugin.
