### ISSUE TITLE
Specific / explicit version syntax not working

### ISSUE THREAD

**Issue by MickeyKay** [kswedberg/grunt-version#14]
It appears that the specific / explicit syntax you mention in #13 isn't working for me. When I type `grunt version::2.01`, I just get the following response:

```
File skipped.
Path: tester-2.php
Current version and new version are equal: 1.0.0
```

Here's my task:
```
version: {
	css: {
		options: {
			prefix: '@version\\s*'
		},
		src: [ 'tester-2.php' ],
	},
},
```

Looks like it's not registering the version number I'm using to call the task directly.

Also, how would this look in a grunt build process? Can I just do something like this:
```
grunt.registerTask( 'build', [
	'clean',
	'version::5.0'
] );
```

Where 5.0 is the version I want to bump to? Is there another way to explicitly specify a specific version to bump to?

Thanks

**Comment by kswedberg** [comment]
Hi @MickeyKay . "5.0" is not valid semver. Try 5.0.0 instead.

For creating a build task, you could do what you mentioned. Or, if you want the version number to be dynamic, you could do it like this:

```js
  grunt.registerTask( 'build', function(arg) {
    var tasks = ['clean'];
    grunt.task.run(tasks);
  });
```

Then on the command line you could do `grunt build:5.0.0`

My example requires a version argument, so just

**Comment by kswedberg** [comment]
Closing this as answered.
