### ISSUE TITLE
Folders named .js

### ISSUE THREAD

**Issue by davewilton** [kswedberg/grunt-version#17]
If the src is set to *.js and a folder exists with the name jimu.js it causes the error "Warning: Unable to read "dist/jimu.js" file (Error code: EISDIR)."

Sorry, I didn't name the library esri did.

**Comment by davewilton** [comment]
Just realised I can use the filter 'isFile' so you may just want to close this

**Comment by kswedberg** [comment]
ok. thanks! Let me know if you run into any other problems.
