### ISSUE TITLE
Switching from grunt-text-replace

### ISSUE THREAD

**Issue by SiamKreative** [kswedberg/grunt-version#18]
Hi there,

I'm currently using https://github.com/yoniholmes/grunt-text-replace to update the version number. I prefer the way your plugin works, as it's really designed for version updates. Here is how I use grunt-text-replace at the moment:

```javascript
replace: {
	pluginVersion: {
		src: [
			'plugin-reviews.php'
		],
		overwrite: true,
		replacements: [{
			from: /^Version: .*$/m,
			to: 'Version:           <%= pkg.version %>'
		}]
	},
	pluginConstant: {
		src: [
			'plugin-reviews.php'
		],
		overwrite: true,
		replacements: [{
			from: /define\( '(.*?)',\s*'(.*)' \);/,
			to: 'define( \'WR_VERSION\', \'<%= pkg.version %>\' );'
		}]
	},
	stableTag: {
		src: [
			'readme.txt'
		],
		overwrite: true,
		replacements: [{
			from: /^Stable tag: .*$/m,
			to: 'Stable tag: <%= pkg.version %>'
		}]
	}
},
```

I suck at creating regex that works, even with the help of online tools. So perhaps you could let me know if the above 3 cases could work with your plugin?

Thanks

**Comment by kswedberg** [comment]
@SiamKreative I'll take a look this weekend and post something for you.

**Comment by kswedberg** [comment]
@SiamKreative : I'm not sure about the pluginConstant one. I'd have to see some examples of what the line of text looks like before and after. For the other two, you could do something like this:

```js
version: {
  siamPlugin: {
    options: {
      prefix: 'Version:\\s+'
    },
    src: [
      'plugin-reviews.php'
    ]
  },
  stableTag: {
    options: {
      prefix: 'Stable tag:\\s+'
    },
    src: [
      'readme.txt'
    ]
  }
}
```

**Comment by kswedberg** [comment]
@SiamKreative I just took a look at an earlier version of your request, and I think I have a solution for the `pluginConstant` one:

```js
pluginConstant: {
  options: {
    prefix: 'define\\(\\s*\'WR_VERSION\',\\s*\''
  },
  src: [
    'plugin-reviews.php'
  ]
}
```

So using that one along with the other two should get you want you want.

**Comment by SiamKreative** [comment]
Thank you do much for your help Karl! It works perfectly :+1: (see https://github.com/ThemeAvenue/Plugin-Reviews/commit/c94db800c38378a677eab4270b4e28fb256ce0f0)
