### ISSUE TITLE
Updating only first version found in file (composer.json issue)

### ISSUE THREAD

**Issue by pkollitsch** [kswedberg/grunt-version#21]
In composer.json files we sometimes have multiple items with versions. The task updates all versions to the new one.

grunt task:
<pre>project: {
  options: {
    release: 'patch'
  },
  src: ['package.json', 'bower.json', 'composer.json']
},</pre>

composer file (sample)
<pre>{
  "version": "5.0.10",
  ... etc ...
  "repositories":[
  {
    "type"   : "package",
    "package": {
      "name"   : "wordpress",
      "type"   : "webroot",
      **"version": "4",**
      ... etc ...
    }
  },
],
</pre>

the version number inside of the repositories path should not be updated.

it there any way to update only the first occurrence of version or a way to somehow regexp to only a version tag in the root level of the json?

**Comment by kswedberg** [comment]
Sorry for the delay in getting back to you! You should be able to set the `flags` option to an empty string. The default is `'g'` (global).

**Comment by pkollitsch** [comment]
Thank you, yes, that did the job :)
