### ISSUE TITLE
[Change Request] Add option to set version via command parameter

### ISSUE THREAD

**Issue by Althain** [kswedberg/grunt-version#23]
Hello there,

I find your task/plugin very useful and I'm thankful for it, however I need one more possibility that I miss and it could be useful for a wider range of people. 
The missing possibility is to directly set the version via command parameter, no increment than while parameter is provided etc. 
Please let me know if this is something to be done and will be done.

Thanks,
Althain

**Comment by kswedberg** [comment]
Have you tried setting the version directly with the `release` option? If it's a valid semver release (x.x.x) it should work. https://github.com/kswedberg/grunt-version#optionsrelease

**Comment by Althain** [comment]
@kswedberg yes, this is what I meant, I haven't seen the sentence telling that you can type the version there directly. Thank you for your help, sorry for bother and the issue is to be closed or deleted.
