### ISSUE TITLE
only write version if it different

### ISSUE THREAD

**Issue by droid51** [kswedberg/grunt-version#9]
hi there,

how about writing a file only if the verysion number is different?
Because it change the modification-date of the file.
Thanks!

if (!matches) {
        grunt.log.subhead('Pattern not found in file');
        grunt.log.writeln('Path: ' + filepath);
        grunt.log.writeln('Pattern: ' + pattern);
      } else {
        **var fileVersion =  matches.pop();**
        grunt.log.subhead('File updated');
        grunt.log.writeln('Path: ' + filepath);
        grunt.log.writeln('Old version: ' + **fileVersion** + '. New version: ' + version + '.');
      }
      **if(version != fileVersion){**
        grunt.file.write(filepath, newfile);
      **}**

**Comment by crazyx13th** [comment]
Hi there,
npm ERR! Error: version not found: grunt-version@0.3.1
only 0.3.0 :-(

thx

**Comment by kswedberg** [comment]
@crazyx13th sorry about that. Version 0.3.1 is now published.
